version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: service_db
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U local -d local"]
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://local:local@db:5432/service_db
      PYTHONUNBUFFERED: 1
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://local:local@db:5432/service_db
      PYTHONUNBUFFERED: 1
    volumes:
      - .:/app
    command: bash -c "pytest -s -x -vv --cov=src"


volumes:
  postgres_data: